# Generated by Django 6.0.6 on 2026-07-12 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='photo',
            field=models.URLField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
