# Generated by Django 6.0.6 on 2026-07-12 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_master_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='master',
            old_name='expirience_years',
            new_name='experience_years',
        ),
    ]
