# Generated by Django 6.0.6 on 2026-07-12 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_service_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='full_description',
            field=models.TextField(blank=True),
        ),
    ]
