# Generated by Django 6.0.6 on 2026-07-12 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_service_full_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='photo',
            field=models.URLField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
