# Generated by Django 6.0.6 on 2026-07-04 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MasterSchedules',
            new_name='MasterSchedule',
        ),
    ]
